sudo: required
language: python
python: 2.7
cache: pip
services:
  - docker
env:
  - ANSIBLE=2.6
  - ANSIBLE=2.7
install:
  - pip install ansible==${ANSIBLE} ansible-lint>=4.0.0 molecule==1.25.0 docker git-semver testinfra>=1.7.0
before_script:
  - ansible-lint tests/playbook.yml
script:
  - molecule test
branches:
  only:
    - master
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
