---
galaxy_info:
  author: "Xavier Binois"
  description: "Install and configure MariaDB with Ansible"
  role_name: mariadb
  license: "GNU General Public License v3.0"
  min_ansible_version: 2.8

  platforms:
    - name: "Debian"
      versions:
        - "buster"

  galaxy_tags:
    - mariadb
    - database
    - sql
    - data

dependencies: []
