---
- name: Reload systemd
  systemd:
    daemon_reload: true
  notify: Service started

- name: Service started
  service:
    name: "{{ mariadb_daemon }}"
    state: started
    enabled: true

- name: Restart MariaDB
  service:
    name: "{{ mariadb_daemon }}"
    state: restarted
