---
- hosts: docker-swarm
  become: true
  become_user: root
  tasks:

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt:
        pkg:
          - nfs-common
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

- hosts: docker-swarm
  become: true
  become_user: root

  tasks:

#    - name: Create mountable dir
#      file: path=/mnt/docker-data state=directory mode=777 owner=root group=root

    - name: set mountpoints
      mount: name=/mnt/docker-data src=nova.int.whitehome.io:/mnt/user/dkrswarm fstype=nfs opts=defaults dump=0 passno=2 state=mounted
